[project]
name = "cream"
version = "0.0a-pre"
author = "lemonbrass"
description = "Cream- the c3 buildsystem"
sources = ["src/"]
build-directory = "build"

[target.release]
flags = "-O5 -g0"
after-build = "echo 'built'"

[target.debug]
flags = "-O0 -g"

[test.mycmd]
type = "command"
command = "echo 'testing, 1 2 3, OK, yeah'"

[test.mysrc]
type = "script"
sources = [ "tests" ]

[install]
for-all = "cp ./build/cream ~/.bin/cream"

[extern-c.ahaha]
build-command = "cmake --build --/build/"
url = "gitown.com/ahaha"
commit-id = "69"
clone-flags = "--depth=1"
libs = ["mylib"]

# external c projects can be added easily just by:
# 
# [external.c.projname]
# url = "git url"
# git_flags = "git clone flags"
# build_cmd = ""
# commit_id = "git commit id to use"
# flags = "flags"
# output = "--/bin/"
# use = [ "--/bin/mylib.a", "--/bin/mylib3.a" ]
# link = true
#
# --/ means the external project clone directory


# OR you can add custom c3 projects
# c3 projects are directly included, no need to link them 
# however, adding custom build command to build it seperately
#
# [external.c3.projname]
# url = "git url"
# include_dir = ["--/src/"]
# build = "--/bin/"
# use = [.... snip]
# link = true



